package es.javierub.argus.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a unit of code prepared for semantic search.
 *
 * <p>In addition to the content and its position in the file, it stores the
 * identifiers needed to associate the chunk with its project and source file,
 * together with the vector generated by the embedding model. Constructors,
 * getters, setters, and equality methods are generated by Lombok.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CodeChunk {
    /** Unique chunk identifier within the index. */
    private String chunkId;
    /** Identifier of the project to which the chunk belongs. */
    private String projectId;
    /** Identifier of the source file. */
    private String fileId;

    /** File path relative to the project root. */
    private String relativePath;

    /** First line of the chunk, using zero-based numbering. */
    private int startLine;
    /** Last line of the chunk. */
    private int endLine;
    /** Position of the chunk in the file's chunk sequence. */
    private int chunkIndex;

    /** Textual content of the chunk. */
    private String content;

    /** Language detected from the file extension. */
    private String language;
    /** SHA-256 hash of the file when the chunk was generated. */
    private String fileSha256;
    /** Embedding vector associated with the chunk content. */
    private float[] embedding;
}
