package es.javierub.argus.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Summarizes the result of an incremental indexing run.
 *
 * <p>It includes detected changes, the number of processed items, and the
 * durations measured during the operation. Constructors, getters, setters, and
 * equality methods are generated by Lombok.</p>
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class IndexReport {
    /** Root path of the indexed project. */
    private String projectRoot;

    /** Number of newly detected files. */
    private int newFiles;
    /** Number of existing files whose content changed. */
    private int modifiedFiles;
    /** Number of files no longer present in the project. */
    private int deletedFiles;
    /** Number of files retained without reprocessing. */
    private int unchangedFiles;

    /** Total number of files processed during this run. */
    private int processedFiles;
    /** Total number of chunks generated for processed files. */
    private int processedChunks;
    /** Total indexing duration, in milliseconds. */
    private long durationMs;
    /** Accumulated processing time for reindexed files, in milliseconds. */
    private long durationEmbeddingMs;

}
