package es.javierub.argus.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.nio.file.Path;
import java.time.Instant;

/**
 * Describes a file included in a project's index.
 *
 * <p>The instance combines the file identity and location, its file-system
 * properties, and the data from the latest indexing operation. Constructors,
 * getters, setters, and equality methods are generated by Lombok.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class IndexedFile {
    /** Identifier of the project to which the file belongs. */
    private String projectId;
    /** Stable identifier derived from the file path. */
    private String fileId;
    /** SHA-256 hash of the file content. */
    private String sha256;

    /** Absolute file-system path. */
    private Path path;
    /** File path relative to the project root. */
    private String relativePath;

    /** Number of chunks generated during indexing. */
    private int chunkCount;

    /** File size in bytes when it was recorded. */
    private long sizeBytes;
    /** File's last-modified timestamp. */
    private Instant modifiedAt;
    /** Timestamp when this indexing information was created. */
    private Instant indexedAt;
    /** Time spent processing this file, in milliseconds. */
    private long indexationMs;
}
