package es.javierub.argus.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Input data for requesting project indexing.
 *
 * <p>Constructors, getters, setters, and equality methods are generated by
 * Lombok.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class IndexRequest {
    /** Root path of the project to index; it must not be blank. */
    @NotBlank
    private String projectRoot;
}
