spring.application.name=ARGUS

server.port=8081

# H2
spring.datasource.url=jdbc:h2:file:~/.argus/argus;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.ai.model.chat=ollama
spring.ai.model.embedding=ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen2.5-coder:3b
spring.ai.ollama.embedding.model=embeddinggemma:300m

spring.http.clients.imperative.factory=jdk
spring.http.clients.reactive.connector=jdk

management.endpoints.web.exposure.include=health,info

app.indexed-files-root=${user.home}/.argus/indexed-files
app.json-root=${user.home}/.argus/debug
app.chunks-root=${user.home}/.argus/chunks
app.indexing.max-file-size-bytes=3145728